In [2]:
#Array Cration

import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#2D Array

b = np.array([[1,2,3],[4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [4]:
#Array Attribute

a = np.array([1,2,3,4,5,6,7,8,9])

print(a.shape)   #Shape of the array
print(a.size)    #Total element in given array
print(a.dtype)   #Data type of the given array

(9,)
9
int64


In [7]:
#Special Array Creation funtions

a = np.zeros((3,4))
print(a)

b = np.ones((3,4))
print(b)

c = np.arange(1,11,1)
print(c)

d = np.eye(3)
print(d)

e = np.linspace(1,10,5)
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1.    3.25  5.5   7.75 10.  ]


In [9]:
#Random and Reshape function

a = np.random.randint(1,100,12)
print(a)

b = np.random.randint(1,100,12).reshape(3,4)
print(b)

[36 11 87 67 10 78  7 59 69 45 17 63]
[[80 66 12 83]
 [ 4 53 24 41]
 [38 18 70 81]]


In [17]:
#Indexing and Slicing

a = np.arange(1,100,12)
print(a)
print(a[0])
print(a[2])

for i in range(len(a)):
    print(a[i])

print(a[0:8:2])    

[ 1 13 25 37 49 61 73 85 97]
1
25
1
13
25
37
49
61
73
85
97
[ 1 25 49 73]
