In [22]:
#Inserting

import numpy as np

a = np.array([1,2,3,4])
b = np.insert(a,2,5)
print(b)
print(a)

[1 2 5 3 4]
[1 2 3 4]


In [23]:
#Appending

a = np.array([1,2,3,4,5])

b = np.append(a,[6,7])
print(b)

[1 2 3 4 5 6 7]


In [27]:
#Concatenate

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [28]:
#Deleted

a = np.array([1,2,3,4])

b = np.delete(a,2)
print(b)

[1 2 4]


In [29]:
#Staking
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [33]:
#splitting

a = np.array([1,2,3,4,5,6])

print(np.split(a,2))

[array([1, 2, 3]), array([4, 5, 6])]


In [35]:
#Broadcasting

a = np.array([1,2,3,4,5])
b = a*100
print(a)
print(b)

[1 2 3 4 5]
[100 200 300 400 500]
