In [8]:
#Accessing & slice in 2D Array
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)
print(a[1][1])
print(a[0][1])


[[1 2]
 [3 4]]
4
2


In [9]:
#mathematical operation (Vectorization)

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 4 9]


In [15]:
#stastical functions

a = np.array([1,2,3,4,5,6])

print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.std(a))
print(np.median(a))

6
1
21
1.707825127659933
3.5


In [18]:
#Matrix Operations

a = np.array([[1,2],[4,5]])
b = np.array([[4,5,6],[7,8,9]])

print(np.dot(a,b))
print(a.T)

[[18 21 24]
 [51 60 69]]
[[1 4]
 [2 5]]


In [19]:
#Aggregation

a = np.array([[1,2,3],[4,5,6]])

print(np.sum(a, axis = 1))
print(np.sum(a,axis = 0))

[ 6 15]
[5 7 9]


In [20]:
#Boolean Filtering

a = np.array([10,20,30,40,50,60,70])

print(a[a>40])

[50 60 70]
